#### imports

In [1]:
import pandas as pd
import numpy as np
print('Done!')

Done!

#### helper functions

#### read in data

In [2]:
# pulls the stats for every player in the nba
tables = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2025_per_game.html#per_game_stats')
df = tables[0]

#show
df

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,Shai Gilgeous-Alexander,26.0,OKC,PG,76.0,76.0,34.2,11.3,21.8,...,0.9,4.1,5.0,6.4,1.7,1.0,2.4,2.2,32.7,"MVP-1,DPOY-10,CPOY-8,AS,NBA1"
1,2.0,Giannis Antetokounmpo,30.0,MIL,PF,67.0,67.0,34.2,11.8,19.7,...,2.2,9.7,11.9,6.5,0.9,1.2,3.1,2.3,30.4,"MVP-3,DPOY-8,AS,NBA1"
2,3.0,Nikola Jokić,29.0,DEN,C,70.0,70.0,36.7,11.2,19.5,...,2.9,9.9,12.7,10.2,1.8,0.6,3.3,2.3,29.6,"MVP-2,CPOY-2,AS,NBA1"
3,4.0,Luka Dončić,25.0,2TM,PG,50.0,50.0,35.4,9.2,20.5,...,0.8,7.4,8.2,7.7,1.8,0.4,3.6,2.5,28.2,NaN
4,4.0,Luka Dončić,25.0,DAL,PG,22.0,22.0,35.7,9.8,21.2,...,0.7,7.6,8.3,7.8,2.0,0.4,3.4,2.6,28.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,566.0,Jahlil Okafor,29.0,IND,C,1.0,0.0,3.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN
732,567.0,Zyon Pullin,23.0,MEM,SG,3.0,0.0,1.0,0.0,0.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
733,568.0,Isaiah Stevens,24.0,MIA,PG,3.0,0.0,2.0,0.0,0.7,...,0.0,0.7,0.7,0.0,0.3,0.0,0.0,0.0,0.0,NaN
734,569.0,Terry Taylor,25.0,SAC,PF,3.0,0.0,2.0,0.0,0.3,...,0.3,0.0,0.3,0.7,0.0,0.0,0.0,0.0,0.0,NaN
735,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# making a dictionary of the teams win proportions
dict_win = {'OKC': [0.829],
            'MIL': [0.585],
            'DEN': [0.610],
            'DAL': [0.476],
            'LAL': [0.610],
            'MIN': [0.598],
            'BOS': [0.744],
            'PHO': [0.439],
            'PHI': [0.293],
            'DET': [0.537],
            'NYK': [0.622],
            'ORL': [0.500],
            'CHO': [0.232],
            'NOP': [0.256],
            'GSW': [0.585],
            'SAS': [0.415],
            'ATL': [0.488],
            'CLE': [0.780],
            'BRK': [0.317],
            'MIA': [0.451],
            'SAC': [0.488],
            'CHI': [0.476],
            'MEM': [0.585],
            'LAC': [0.610],
            'TOR': [0.366],
            'HOU': [0.634],
            'WAS': [0.220],
            'IND': [0.610],
            'POR': [0.439],
            'UTA': [0.207]
}
df_win = pd.DataFrame(dict_win) # turning it into a data frame
df_win = df_win.melt(var_name='Team') # making it long format for the merge

# show
df_win

   Team  value
0   OKC  0.829
1   MIL  0.585
2   DEN  0.610
3   DAL  0.476
4   LAL  0.610
5   MIN  0.598
6   BOS  0.744
7   PHO  0.439
8   PHI  0.293
9   DET  0.537
10  NYK  0.622
11  ORL  0.500
12  CHO  0.232
13  NOP  0.256
14  GSW  0.585
15  SAS  0.415
16  ATL  0.488
17  CLE  0.780
18  BRK  0.317
19  MIA  0.451
20  SAC  0.488
21  CHI  0.476
22  MEM  0.585
23  LAC  0.610
24  TOR  0.366
25  HOU  0.634
26  WAS  0.220
27  IND  0.610
28  POR  0.439
29  UTA  0.207

In [6]:
# merge them together
df_stats = pd.merge(left=df, right=df_win, how='left', left_on='Team', right_on='Team')
dict_rename = {'value': 'Team_Win'} # renames the 'value' column to 'Team_Win'
df_stats = df_stats.rename(dict_rename, axis=1)

# show
df_final

,index,Rk,Player,Age,Team,Pos,G,GS,MP,FG,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Team_Win
0,0,1.0,Shai Gilgeous-Alexander,26.0,OKC,PG,76.0,76.0,34.2,11.3,...,4.1,5.0,6.4,1.7,1.0,2.4,2.2,32.7,"MVP-1,DPOY-10,CPOY-8,AS,NBA1",0.829
1,1,2.0,Giannis Antetokounmpo,30.0,MIL,PF,67.0,67.0,34.2,11.8,...,9.7,11.9,6.5,0.9,1.2,3.1,2.3,30.4,"MVP-3,DPOY-8,AS,NBA1",0.585
2,2,3.0,Nikola Jokić,29.0,DEN,C,70.0,70.0,36.7,11.2,...,9.9,12.7,10.2,1.8,0.6,3.3,2.3,29.6,"MVP-2,CPOY-2,AS,NBA1",0.610
3,4,4.0,Luka Dončić,25.0,DAL,PG,22.0,22.0,35.7,9.8,...,7.6,8.3,7.8,2.0,0.4,3.4,2.6,28.1,NaN,0.476
4,5,4.0,Luka Dončić,25.0,LAL,PG,28.0,28.0,35.1,8.8,...,7.2,8.1,7.5,1.6,0.4,3.7,2.4,28.2,NaN,0.610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649,730,565.0,Riley Minix,24.0,SAS,SF,1.0,0.0,7.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.415
650,731,566.0,Jahlil Okafor,29.0,IND,C,1.0,0.0,3.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.610
651,732,567.0,Zyon Pullin,23.0,MEM,SG,3.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.585
652,733,568.0,Isaiah Stevens,24.0,MIA,PG,3.0,0.0,2.0,0.0,...,0.7,0.7,0.0,0.3,0.0,0.0,0.0,0.0,NaN,0.451
653,734,569.0,Terry Taylor,25.0,SAC,PF,3.0,0.0,2.0,0.0,...,0.0,0.3,0.7,0.0,0.0,0.0,0.0,0.0,NaN,0.488

In [7]:
# drop the rows that don't have a team win
df_stats = df_stats.dropna(subset=['Team_Win'])
df_stats.reset_index(inplace=True) # resets the index after dropping

# show
df_stats

,index,Rk,Player,Age,Team,Pos,G,GS,MP,FG,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Team_Win
0,0,1.0,Shai Gilgeous-Alexander,26.0,OKC,PG,76.0,76.0,34.2,11.3,...,4.1,5.0,6.4,1.7,1.0,2.4,2.2,32.7,"MVP-1,DPOY-10,CPOY-8,AS,NBA1",0.829
1,1,2.0,Giannis Antetokounmpo,30.0,MIL,PF,67.0,67.0,34.2,11.8,...,9.7,11.9,6.5,0.9,1.2,3.1,2.3,30.4,"MVP-3,DPOY-8,AS,NBA1",0.585
2,2,3.0,Nikola Jokić,29.0,DEN,C,70.0,70.0,36.7,11.2,...,9.9,12.7,10.2,1.8,0.6,3.3,2.3,29.6,"MVP-2,CPOY-2,AS,NBA1",0.610
3,4,4.0,Luka Dončić,25.0,DAL,PG,22.0,22.0,35.7,9.8,...,7.6,8.3,7.8,2.0,0.4,3.4,2.6,28.1,NaN,0.476
4,5,4.0,Luka Dončić,25.0,LAL,PG,28.0,28.0,35.1,8.8,...,7.2,8.1,7.5,1.6,0.4,3.7,2.4,28.2,NaN,0.610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649,730,565.0,Riley Minix,24.0,SAS,SF,1.0,0.0,7.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.415
650,731,566.0,Jahlil Okafor,29.0,IND,C,1.0,0.0,3.0,0.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.610
651,732,567.0,Zyon Pullin,23.0,MEM,SG,3.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.585
652,733,568.0,Isaiah Stevens,24.0,MIA,PG,3.0,0.0,2.0,0.0,...,0.7,0.7,0.0,0.3,0.0,0.0,0.0,0.0,NaN,0.451
653,734,569.0,Terry Taylor,25.0,SAC,PF,3.0,0.0,2.0,0.0,...,0.0,0.3,0.7,0.0,0.0,0.0,0.0,0.0,NaN,0.488

In [13]:
tables = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2025_advanced.html')
df_advanced = tables[0]

df_advanced

,Rk,Player,Age,Team,Pos,G,GS,MP,PER,TS%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards
0,1.0,Mikal Bridges,28.0,NYK,SF,82.0,82.0,3036.0,14.0,0.585,...,19.6,3.7,2.0,5.7,0.090,0.4,-0.9,-0.5,1.2,NaN
1,2.0,Josh Hart,29.0,NYK,SG,77.0,77.0,2897.0,16.5,0.611,...,15.3,5.4,3.8,9.2,0.153,1.1,1.8,2.8,3.6,NaN
2,3.0,Anthony Edwards,23.0,MIN,SG,79.0,79.0,2871.0,20.1,0.595,...,31.4,4.6,3.8,8.4,0.140,4.4,0.0,4.3,4.6,"MVP-7,CPOY-3,AS,NBA2"
3,4.0,Devin Booker,28.0,PHO,SG,75.0,75.0,2795.0,19.3,0.589,...,29.3,6.1,0.3,6.4,0.111,2.8,-2.4,0.4,1.7,NaN
4,5.0,James Harden,35.0,LAC,PG,79.0,79.0,2789.0,20.0,0.582,...,29.6,4.0,4.3,8.3,0.143,3.5,0.8,4.3,4.4,"MVP-10,AS,NBA3"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,566.0,James Wiseman,23.0,IND,C,1.0,0.0,5.0,31.2,0.615,...,42.2,0.0,0.0,0.0,0.237,6.0,-4.4,1.6,0.0,NaN
732,567.0,Alondes Williams,25.0,DET,SG,1.0,0.0,4.0,53.4,1.250,...,21.1,0.0,0.0,0.0,0.565,37.9,6.2,44.1,0.0,NaN
733,568.0,Zyon Pullin,23.0,MEM,SG,3.0,0.0,3.0,-11.7,0.000,...,13.4,0.0,0.0,0.0,-0.304,-15.0,-7.7,-22.7,0.0,NaN
734,569.0,Jahlil Okafor,29.0,IND,C,1.0,0.0,3.0,13.8,NaN,...,0.0,0.0,0.0,0.0,0.196,2.5,4.9,7.5,0.0,NaN
735,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.576,...,19.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
cols_drop = ['Age', 'Pos', 'G', 'GS', 'Awards']

df_advanced = df_advanced.drop(cols_drop, axis=1)

df_advanced

,Rk,Player,Team,MP,PER,TS%,3PAr,FTr,ORB%,DRB%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,1.0,Mikal Bridges,NYK,3036.0,14.0,0.585,0.391,0.100,2.7,7.0,...,9.7,19.6,3.7,2.0,5.7,0.090,0.4,-0.9,-0.5,1.2
1,2.0,Josh Hart,NYK,2897.0,16.5,0.611,0.327,0.266,6.4,22.6,...,15.5,15.3,5.4,3.8,9.2,0.153,1.1,1.8,2.8,3.6
2,3.0,Anthony Edwards,MIN,2871.0,20.1,0.595,0.503,0.308,2.4,14.8,...,12.0,31.4,4.6,3.8,8.4,0.140,4.4,0.0,4.3,4.6
3,4.0,Devin Booker,PHO,2795.0,19.3,0.589,0.388,0.340,3.1,8.9,...,11.9,29.3,6.1,0.3,6.4,0.111,2.8,-2.4,0.4,1.7
4,5.0,James Harden,LAC,2789.0,20.0,0.582,0.516,0.446,2.3,16.1,...,18.0,29.6,4.0,4.3,8.3,0.143,3.5,0.8,4.3,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,566.0,James Wiseman,IND,5.0,31.2,0.615,0.250,0.500,0.0,22.1,...,0.0,42.2,0.0,0.0,0.0,0.237,6.0,-4.4,1.6,0.0
732,567.0,Alondes Williams,DET,4.0,53.4,1.250,0.500,0.000,0.0,0.0,...,0.0,21.1,0.0,0.0,0.0,0.565,37.9,6.2,44.1,0.0
733,568.0,Zyon Pullin,MEM,3.0,-11.7,0.000,0.000,0.000,0.0,0.0,...,0.0,13.4,0.0,0.0,0.0,-0.304,-15.0,-7.7,-22.7,0.0
734,569.0,Jahlil Okafor,IND,3.0,13.8,NaN,NaN,NaN,0.0,36.8,...,NaN,0.0,0.0,0.0,0.0,0.196,2.5,4.9,7.5,0.0
735,NaN,League Average,NaN,NaN,NaN,0.576,0.421,0.243,5.0,15.0,...,12.0,19.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_statsadvanced = pd.merge(left=df_stats, right=df_advanced, how='left', left_on=['Player', 'Team'], right_on=['Player', 'Team'])

df_statsadvanced

,index,Rk_x,Player,Age,Team,Pos,G,GS,MP_x,FG,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,0,1.0,Shai Gilgeous-Alexander,26.0,OKC,PG,76.0,76.0,34.2,11.3,...,8.6,34.8,11.9,4.8,16.7,0.309,8.9,2.6,11.5,8.9
1,1,2.0,Giannis Antetokounmpo,30.0,MIL,PF,67.0,67.0,34.2,11.8,...,11.2,35.2,7.8,3.7,11.5,0.241,6.9,2.5,9.5,6.6
2,2,3.0,Nikola Jokić,29.0,DEN,C,70.0,70.0,36.7,11.2,...,12.8,29.5,12.7,3.8,16.4,0.307,9.9,3.3,13.3,9.8
3,4,4.0,Luka Dončić,25.0,DAL,PG,22.0,22.0,35.7,9.8,...,12.4,33.1,1.5,1.1,2.5,0.155,5.5,1.4,6.9,1.8
4,5,4.0,Luka Dončić,25.0,LAL,PG,28.0,28.0,35.1,8.8,...,13.5,34.5,2.0,1.4,3.4,0.164,5.5,1.1,6.5,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649,730,565.0,Riley Minix,24.0,SAS,SF,1.0,0.0,7.0,0.0,...,0.0,6.1,0.0,0.0,0.0,-0.114,-8.5,-3.3,-11.8,0.0
650,731,566.0,Jahlil Okafor,29.0,IND,C,1.0,0.0,3.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0.196,2.5,4.9,7.5,0.0
651,732,567.0,Zyon Pullin,23.0,MEM,SG,3.0,0.0,1.0,0.0,...,0.0,13.4,0.0,0.0,0.0,-0.304,-15.0,-7.7,-22.7,0.0
652,733,568.0,Isaiah Stevens,24.0,MIA,PG,3.0,0.0,2.0,0.0,...,0.0,14.8,0.0,0.0,0.0,-0.196,-19.5,7.7,-11.8,0.0
653,734,569.0,Terry Taylor,25.0,SAC,PF,3.0,0.0,2.0,0.0,...,0.0,7.2,0.0,0.0,0.0,0.049,3.2,0.1,3.3,0.0

In [17]:
# save it to a csv
df_statsadvanced.to_csv('./player_data.csv')